general:
  working_dir: ./
  resources_dir: ./resources
  logging_level: DEBUG
  api_version: 1.0.0.0

stereo_processor:
  path_to_unzip: data/extracted
  threshold: 1000

label_creator:
  path_to_data: data/clouds_tof
  result_json: data/clouds_tof.json

train:
  path_to_dataset: data/dataset.json

flask:
  SECRET_KEY: very-long-and-very-secret-key
  ORIGINS: ['http://127.0.0.1:8080', 'http://localhost:8080']
  SQLALCHEMY_ECHO: False # если True, то SQLAlchemy выводит все сообщения в stderr
  SQLALCHEMY_TRACK_MODIFICATIONS: False # если True, то Flask-SQLAlchemy отслеживает изменения объектов и посылает соответствующие сигналы
  REMEMBER_COOKIE_DURATION: 600
  REMEMBER_COOKIE_HTTPONLY: False
  REMEMBER_COOKIE_REFRESH_EACH_REQUEST: True